// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
let SolnSquareVerifier = artifacts.require('SolnSquareVerifier');
let SquareVerifier = artifacts.require('SquareVerifier');

contract('SolnSquareVerifier', accounts => {
    // - use the contents from proof.json generated from zokrates steps
    const zkProof = require("../../zokrates/code/square/proof.json");

    describe('test solidity contract generated by Zokrates', function () {
        beforeEach(async function () {
            const squareVerifier = await SquareVerifier.new();
            this.contract = await SolnSquareVerifier.new(squareVerifier.address, {from: accounts[0]});
        })

        // Test if a new solution can be added for contract - SolnSquareVerifier
        it('new solution can be added for contract', async function () {
            const result = undefined;

            const key = await this.contract.generateSolutionKey(
                zkProof.proof.a,
                zkProof.proof.b,
                zkProof.proof.c,
                zkProof.inputs
            );
            result = await this.contract.addSolution(10, accounts[1], key);

            assert.equal(result.logs.length > 0, true, "Verification failed");
        })

        // Test if an ERC721 token can be minted for contract - SolnSquareVerifier
        it('an ERC721 token can be minted for contract', async function () {
            const result = undefined;
            const tokenId = 11;

            result = await this.contract.mintNFT(
                accounts[2],
                tokenId,
                zkProof.proof.a,
                zkProof.proof.b,
                zkProof.proof.c,
                zkProof.inputs
            );

            assert.equal(result.logs.length > 0, true, "Verification passed");
        })
    });
})
